baseurl = "https://dysmento.com/"
title = "dysmento on the web"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[security]
  [security.exec]
    allow = ["asciidoctor"]

[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Zach Thomas"
  info = "A Texan in North Carolina"
  description = "dysmento on the web"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "zach.thomas@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2015

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/dysmento/"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/dysmento/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "prod"

# Amazon Web Services S3; see https://gocloud.dev/howto/blob/#s3
URL = "s3://dysmento.com?region=us-east-1"
